### ISSUE TITLE
Trouble with the examples.

### ISSUE THREAD

**Issue by abhi18av** [typelead/eta-examples#2]
Hey, so I tried compiling the examples here, hoping that these might shed more light on https://github.com/typelead/eta/issues/425

I run into errors with the `2-javafx` example. Here's the stack trace

```sh
❯ etlas run
Resolving dependencies...
Configuring eta-javafx-0.1.0.0...
Preprocessing executable 'eta-javafx' for eta-javafx-0.1.0.0..
Building executable 'eta-javafx' for eta-javafx-0.1.0.0..
[1 of 6] Compiling JavaFX.Types     ( src/JavaFX/Types.hs, dist/build/eta-javafx/eta-javafx-tmp/JavaFX/Types.jar )
[2 of 6] Compiling JavaFX.Methods   ( src/JavaFX/Methods.hs, dist/build/eta-javafx/eta-javafx-tmp/JavaFX/Methods.jar )
[3 of 6] Compiling SampleApp        ( src/SampleApp.hs, dist/build/eta-javafx/eta-javafx-tmp/SampleApp.jar )
[4 of 6] Compiling JavaFX.Core      ( src/JavaFX/Core.hs, dist/build/eta-javafx/eta-javafx-tmp/JavaFX/Core.jar )
[5 of 6] Compiling JavaFX           ( src/JavaFX.hs, dist/build/eta-javafx/eta-javafx-tmp/JavaFX.jar )
[6 of 6] Compiling Main             ( src/Main.hs, dist/build/eta-javafx/eta-javafx-tmp/Main.jar )
Linking dist/build/eta-javafx/eta-javafx.jar ...
Running eta-javafx...
Exception in thread "main" java.lang.ClassNotFoundException: noitacilppA.noitacilppa.xfavaj sdnetxe ppAelpmaS.ate.gro
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at main.Main$main1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
	at main.Main$main2.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:264)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:98)
	at eta.runtime.Rts.hsMain(Rts.java:40)
	at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment]
Thanks for reporting this! I encountered this while testing out the upcoming Eta v0.0.9, and it'll be fixed on that.

**Comment by rahulmutt** [comment]
This should be fixed on `master`.
